### ISSUE TITLE
Add limit orders.

### ISSUE THREAD

**Issue by a-triant** [Loopring/loopring-wallet-feedback#115]
Please make ability to trade limit orders from iOS mobile app.

**Comment by sk33z3r** [comment]
@a-triant 

I wonder if this issue post is old and just never got closed. Limit Orders exist in Android and the web app currently, I can't imagine they wouldn't exists on iOS (but I don't have iOS, so I may be wrong).

In the Android app, I go to the **Trading**, then at the top-right there's a tab/button for **Professional**, which is a slightly more complex interface including the option between Limit and Market orders.

**Comment by a-triant** [comment]
Added in version 2.0.23
