### ISSUE TITLE
Push Notifications.

### ISSUE THREAD

**Issue by a-triant** [Loopring/loopring-wallet-feedback#119]
Strange that no one suggested that yet, we need push notifications for incoming and outcoming transactions like probably every wallet already have, also for limit trade orders when they executed should be good to have a notification! Also maybe optional when price goes down or up.

**Comment by sk33z3r** [comment]
I've had two limit orders go through successfully, but it wasn't until hours later when I decided to check the app that I noticed the order had gone through. I'm glad the orders went through successfully, but getting notified when it occurred would have been great for tracking my DCA; I posted another, related issue regarding data of previous orders. There's no real transaction history, either. #154

**Comment by chrisdudek** [comment]
It would be great to have push notifications for:

- Price Alerts
- Limit Orders triggering
- Tokens/NFTs Deposited
- Tokens/NFTs Withdrawn
- Guardian Approvals
- Wallet is accessed by another device (i.e. if someone attempts to Recover or Migrate your wallet onto a different device)

**Comment by a-triant** [comment]
The setting have been added(in iOS), however it's unknown for what types of notifications it is.
Will be better if a new "Notifications" section will be added where you can Enable/Disable plus ability to select which exactly notifications do you want to receive, an great example of list have been written above by @chrisdudek.
