### ISSUE TITLE
L1 and L2 balances shows 0,  despite wallet contains tokens correctly sent.

### ISSUE THREAD

**Issue by tiziano-carrer** [Loopring/loopring-wallet-feedback#12]
I sent LRCs and eth either in L1 or L2 wallet, but balances always shows "zero"

**Comment by autumn8** [comment]
Experiencing the same- Eth deposit does not reflect in wallet (wallet displays $0.00), however the operation records show the transaction and the amount as having been received by the L1 account.

**Comment by tiziano-carrer** [comment]
Solved changing system language from Italian to English/USA
