### ISSUE TITLE
Looping/repeating Relayer API Upgrade message

### ISSUE THREAD

**Issue by PORTAL4545** [Loopring/loopring-wallet-feedback#123]
This is the looping screen we are seeing. Click 'Upgrade' and it takes you to the IOS app store. Go back to the app and it is still there and can't be dismissed. Attaching screenshot
![RelayerError](https://user-images.githubusercontent.com/96481937/146940020-aba6499a-665d-4048-9018-9bcca4bf0eaa.png)
.

**Comment by Jye924** [comment]
fixed
