### ISSUE TITLE
Loopring App (Android 2.0) no security upon closing the app

### ISSUE THREAD

**Issue by YungShogun** [Loopring/loopring-wallet-feedback#126]
There appears to be no security password or fingerprint prompt when launching the wallet on Samsung 21+ 5G (Android v12) even after closing the app or force closing it from the tray.

Please see attached screencap: [Screencap](https://youtu.be/qWSo6-koQQU)

**Comment by zaskale** [comment]
This can be enabled by going to Settings > Security > Open app requires a password.

**Comment by YungShogun** [comment]
> This can be enabled by going to Settings > Security > Open app requires a password.

I guess you didn't watch the screencap ...

**Comment by zaskale** [comment]
> > This can be enabled by going to Settings > Security > Open app requires a password.
> 
> I guess you didn't watch the screencap ...

Looks like I missed the screencap. My mistake.

**Comment by Emphryio** [comment]
I have the same issue with Samsung 21. I have password on for when app launches but it never asks for a password.

**Comment by tommueller** [comment]
Same issue here on an older Sony Xperia running Android 7.1.1!

**Comment by cambobomb** [comment]
Same issue on LG Velvet 5G. LM-G900UM. Android 11.  Kernel 4.19.113

**Comment by YungShogun** [comment]
Since 2.0.4 version update this appears to be resolved on Samsung 21+ 5G (Android v12)

(had to force the manual update from Play Store)

**Comment by tommueller** [comment]
Yes, resolved for me as well!
