### ISSUE TITLE
ux nit: the word transfer is used twice

### ISSUE THREAD

**Issue by yuval-k** [Loopring/loopring-wallet-feedback#13]
when I view the eth 1 balance, The word transfer is used twice:
- one time it means transfer to different L1 address.
- the second time it means transfer to my own L2 address.

Consider different words? maybe 'Send' for the L1 address?

**Comment by yuval-k** [comment]
See image:
![Screenshot_20201124-182553_Loopring wallet](https://user-images.githubusercontent.com/325621/100162944-a2fc4500-2e82-11eb-985d-a59d8fb2a0c8.jpg)

**Comment by mfinestone** [comment]
Thanks Yuval. Known issue. Translations are not very good right now. Big overhaul of English coming after Friday :).

**Comment by tiziano-carrer** [comment]
> when I view the eth 1 balance, The word transfer is used twice:
> 
> * one time it means transfer to different L1 address.
> * the second time it means transfer to my own L2 address.
> 
> Consider different words? maybe 'Send' for the L1 address?

They could use "transfer/send" for L1 and "elevate/lower" for L2
