### ISSUE TITLE
Red Packet unsupported token.

### ISSUE THREAD

**Issue by a-triant** [Loopring/loopring-wallet-feedback#131]
Trying to withdraw some tokens from Red Packets, we have a message "This token is not supported withdrawal" 

![Screenshot 2021-12-26 113000](https://user-images.githubusercontent.com/22340405/147404286-c79b8124-d587-469c-87d3-6e1b1de3cf23.png)

**Comment by rolobrew** [comment]
Having the same issue for some reason you can sent AMM funds but cannot pull them. It auto fills to to AMM when making red packets.  Mine is LRC-USDC

**Comment by a-triant** [comment]
Fixed on iOS 2.0.31
