### ISSUE TITLE
Action buttons on Assets page are too close to Android status banner (Pixel 5)

### ISSUE THREAD

**Issue by Thrilhau5** [Loopring/loopring-wallet-feedback#137]
The action buttons on the wallet assets page are too close to the android status banner.  When trying to select an action, the phone sometimes senses a press of the android banner making it difficult to select the scanner etc.

Apps like discord have these buttons lower down and try not to place anything in that top section as often there is a cutout for the selfie camera as well
![Screenshot_20211229-140747](https://user-images.githubusercontent.com/96805958/147624184-9cba6645-0e6a-494b-8119-05d3459ab644.png)
.

**Comment by Jye924** [comment]
Please upgrade the latest version, and check it. Thank you.
