### ISSUE TITLE
Action buttons on scanner page are too close to android status banner and overlap with the selfie camera cutout (Pixel 5)

### ISSUE THREAD

**Issue by Thrilhau5** [Loopring/loopring-wallet-feedback#138]
Action buttons up the top of the scanner page (when scanner is active) are too high up and interact with other android buttons.  The left hand side "back" button is also half covered by the Pixel 5 camera cutout.  Suggest these buttons be lower to ensure compatibility across different android phone models.
![Screenshot_20211229-140826](https://user-images.githubusercontent.com/96805958/147624335-b49a0370-3c1c-4de0-88cc-289ddeffd5de.png)

**Comment by kinaaro** [comment]
Hi,

I have been redirected here to comment that I am also experiencing the same issues regarding the buttons located towards the top of the app too. I'm also using a Pixel 5. Please see the attached images for reference. 

![Screenshot_20220124-112736](https://user-images.githubusercontent.com/98322293/150780445-27075529-399c-4c5a-aed0-0c3c1e291b9f.png)
![Screenshot_20220124-112853](https://user-images.githubusercontent.com/98322293/150780474-a8c28379-cc17-43e4-acaa-55ce6fd5bb9b.png)

**Comment by svartfogel** [comment]
Same issue as mine https://github.com/Loopring/loopring-wallet-feedback/issues/163#issue-1140941933
