### ISSUE TITLE
Email cannot be used again after creation time expiry

### ISSUE THREAD

**Issue by mfinestone** [Loopring/loopring-wallet-feedback#15]
From user tjumma:

Hello, guys! I have a problem - yesterday I started creating a new wallet, but my creation time (1 day) has expired, I pressed create a new one to select a different name for it, but the app does not let me use the same email - it says 'The email has been registered before'

-- Is there a solution for this?

**Comment by mfinestone** [comment]
Answer from Keith: we give them extra 12 hours to finish deposit to their wallet address, in case some pending tx delay on the ethereum, so they could reuse their email  after 36 hours from they submit creation wallet request.

**Comment by ablankstory** [comment]
We also now allow users to change email address after setting up 2FA.
