### ISSUE TITLE
Nft Minting android wallet and windows chrome browser stuck after approval

### ISSUE THREAD

**Issue by Nimai85** [Loopring/loopring-wallet-feedback#164]
These are the steps:
open loopring.io website on chrome (icognito or not it's the same)
connect an android L2 wallet with wallect connect
from mynft page click on mint nft
paste the CID from pinata cloud and i see the metadata and the preview correctly
proceed and approve on android device
the screen on the loopring.io page stays on the Allow Loopring to Mint... screen

**Comment by sk33z3r** [comment]
Identical behavior here. I have tried in both Firefox and Brave browsers multiple times.

I never see a transaction appear in my history, and the approve message doesn't outright tell me what the fee is going to be. There is an indication of the fee in the message's json, but not explicitly printed on screen like I would expect in any other approval message that involves fees.

**Comment by wizardking-loopring-eth** [comment]
Identical Error using Google Chrome. When asked to verify transaction to mint via my mobile wallet app... the screeen stays stuck on google chrome desktop of "Allow Loopring to Mint Commando"


![Error](https://user-images.githubusercontent.com/100399742/155860394-40a59c9f-2103-4548-be6c-7b54f81656e6.PNG)

**Comment by blissid95** [comment]
Also exact same thing happening to me on Android.

**Comment by joshfryart** [comment]
ANDROID Phone using Loopring Smart Wallet
FireFox Browser, all extensions removed.

I can get to the step that asks me to approve the mint on my Loopring App. I hit approve, and then the website just hangs here. 

Hoping for a fix soon. So much art to NFTifize. Thanks for the tools, loopring!

**Comment by syafiqrokman** [comment]
Reproducable on Android + windows Google Chrome 

Loopring Wallet v2.1.3.179
Android 12 (build no SQ1A.220205.002)

Google chrome v98.0.4758.102

**Comment by zhivak** [comment]
Same here, Android Loopring Wallet v2.1.3.179 with Firefox 97.0.1 64bit

**Comment by NovusRex** [comment]
Got the same issue. It gets stuck at the point of approval from the android app. Doesn't seem to actually approve something so I don't think the request is getting sent. Help us with a fix for that :D

**Comment by chadprater** [comment]
Having the same issue. Does all the approvals, but after it does the actual final mint approval on the phone it never completes on the browser. Just keeps hanging and saying "Allow Loopring to mint..." but never does.

**Comment by zhivak** [comment]
We have development. I managed to submit a Mint.
Try and check it!
Good job!

**Comment by chadprater** [comment]
Success! I just minted my first NFT! Woohoo!

**Comment by jamaya23** [comment]
I have been able to mint an NFT. Thanks for fixing so quickly.

**Comment by sk33z3r** [comment]
@Nimai85 Since you're the OP, it seems you would need to be the one to close this. I think it's safe to say this is licked, anything else should be posted as a new bug.

I can confirm on my side, I have successfully minted and deployed my contract. Thanks Loopring Team!

**Comment by Nimai85** [comment]
I can confirm It now works wonderfully. Thank you and best regards
