### ISSUE TITLE
Back button on "Mint NFT" modal returns user to "Add Layer 2 Assets" modal instead of "Mint NFT"

### ISSUE THREAD

**Issue by sk33z3r** [Loopring/loopring-wallet-feedback#170]
**System**:
* NixOS 21.11
* Firefox 97
* Brave 1.35.101
* Android 11
* Loopring Wallet 2.1.3.179

**Repro**:
1. Use WalletConnect on loopring.io to connect and unlock your wallet
2. Go to L2 Wallet > My NFT
3. Click on "Mint NFT" button in top-right
_OBSERVE_: "Mint NFT" modal pop up appears
4. Enter information for metadata CID, fee token, and quantity to mint
5. Click the button "Mint My NFT"
_OBSERVE_: Modal now asks you to approve a message on your wallet device
6. Click the `<` button in top-left of the modal

**Expected**:
I am returned to the "Mint NFT" modal where I can edit the CID, fee and quantity

**Actual**:
I am shown a modal for "Add Layer 2 Assets"

Here is a gif of what I see:

![gif_20220227_105846](https://user-images.githubusercontent.com/20587571/155890115-6ba3c41a-7df7-4e77-a495-06adbe497e33.gif)

**Comment by ghost** [comment]
Not sure what update resolved this, but it is resolved now.
