### ISSUE TITLE
Asset Distribution graph gets cut-off if your browser window is "skinny"

### ISSUE THREAD

**Issue by sk33z3r** [Loopring/loopring-wallet-feedback#173]
**System**:
* NixOS 21.11
* Firefox 97
* Brave 1.35.101
* Android 11
* Loopring Wallet 2.1.3.179

**Repro**:
1. Use WalletConnect to connect and unlock your wallet on loopring.io
2. Snap your browser window to the left or ride side of your screen, making it taller than it is wide
3. Go to L2 Wallet

**Expected**:
Elements respond to the narrower viewport and resize accordingly

**Actual**:
Asset distribution graph remains the same size and is cutoff in its section

![screenshot_20220227_114827](https://user-images.githubusercontent.com/20587571/155891572-b9bd52c1-0693-41e3-b7da-b8b0a1a648bc.png)

**Comment by ghost** [comment]
Snapping to the right or left of the screen looks better in latest version of the UI
