### ISSUE TITLE
Request: Ability to add email/change phone number

### ISSUE THREAD

**Issue by rmikedown** [Loopring/loopring-wallet-feedback#178]
I signed up for my wallet with my phone number, thinking I would also be able to add my email. But the problem is that is I won't be keeping this phone number much longer as I'm heading overseas. Can you implement a way to add my email for two factor verification?

**Comment by rmikedown** [comment]
I see this issue has been around. See: https://github.com/Loopring/loopring-wallet-feedback/issues/65

Can we please have an update on this?

**Comment by ablankstory** [comment]
This is now possible when enabling 2FA.
