### ISSUE TITLE
Deposit vs Fee. Clarifying for users on creation.  

### ISSUE THREAD

**Issue by mfinestone** [Loopring/loopring-wallet-feedback#18]
Users are confused as to whether the deposit for creation is a fee or they maintain the full assets. We should specify it is NOT a fee.

**Comment by enuoCM** [comment]
This should be a feature with higher priority.

**Comment by ablankstory** [comment]
When creating a wallet, new language now clearly states L2 is a deposit (with small fee) and L1 is a creation fee.
