### ISSUE TITLE
NFTs don't have thumbnails in mobile app

### ISSUE THREAD

**Issue by sk33z3r** [Loopring/loopring-wallet-feedback#180]
**Phone Details**:
* Android 11
* Loopring Wallet v2.1.3.179

**Repro**:
1. Open and unlock wallet app
2. Go to **Collectibles** tab

**Expected**:
Circular thumbnails for each NFT appear next to each NFT in the list

**Actual**:
A generic graphic is displayed

**Comment by ghost** [comment]
Resolved as of Android wallet v2.2.2.188

I also have confirmation from iOS users that it is resolved for them as well.
