### ISSUE TITLE
Ambiguous Deploy Contract behavior for minted NFTs

### ISSUE THREAD

**Issue by sk33z3r** [Loopring/loopring-wallet-feedback#182]
Background: Members on Discord have been curious about the **Deploy Contract** button that appears for NFTs after being minted. We received the following information from @odesium on Discord:

![screenshot_20220227_183149](https://user-images.githubusercontent.com/20587571/155904675-6ab34e6a-4988-461c-a1f5-20a8feb19afd.png)

The issue is that we see some odd behavior with the NFTs if they are not deployed. Some issues include:
* Going to L2 Wallet > My NFTs in the web app will only seem to display the thumbnails of NFTs that have already been deployed, but shows missing images and `--` for a name if one has not been deployed.
* On mobile, if a NFT has not been deployed, it can't be viewed at all.
* ~~Some NFTs that have been created are left undeployed, but some time later it appears that they have been deployed and the user is presented with the **Withdraw** button. The user did not initiate any actions, and no deployment txs appear in their history.~~

---

Questions

* Can we get clarification and documentation on specfiically what the Deploy Contract button is doing or supposed to do? This would help us report specific bugs that might be occurring, and help us to understand what we should expect to happen in either scenario.
* ~~What exactly is being deployed? Members on Discord have reported that deploying once is all that was needed, now all their NFTs (old and future) are already deployed. What would happen if I minted an NFT, sent it to someone else, and then _they_ clicked the deploy contract button? Would that deploy the contract only for their specific NFT, or would it deploy my entire contract making the other person pay for the fees?~~

---

Screenshots:

### How NFTs appear in my web app. Missing images are not deployed, viewable images are.

![screenshot_20220227_174837](https://user-images.githubusercontent.com/20587571/155904737-ff1fadb6-eb3b-4ee4-9e50-dc2fc2336f17.png)

### How NFTs appear in my mobile wallet. `Unknow NFT` are not deployed, others are. `Unknow NFT`s are not viewable in any circumstance, but the named NFTs are viewable if you tap on them.

![signal-2022-02-27-184508_002](https://user-images.githubusercontent.com/20587571/155905164-bc9e4e6a-81bf-407e-816f-f23c3249c0a1.png)

![signal-2022-02-27-184508_001](https://user-images.githubusercontent.com/20587571/155905167-dfc18471-6a71-4a28-92eb-799b1356cc4b.png)

**Comment by jamaya23** [comment]
Same issue. Commenting for visibility on answers to OPs questions.

**Comment by sk33z3r** [comment]
We had a generous user in Discord volunteer to test my second question, and this is exactly how it works. If you mint something, then transfer to someone else, that other person can pay the gas fees to deploy your entire smart contract.

**Comment by sk33z3r** [comment]
The update for the Explorer UI was this fallback function, in case a metadata json is not found:
https://github.com/Loopring/loopring-explorer/commit/9bbf2e6b1ad0c7ac334c1ed98915dfa15f59bb64#diff-8eb9fcb6584b0eceaacb3bf0e762bebe634f0fe12607d521fad3e9feaeeb4954R21

It's not a full solution, but it allows for old and new NFTs to be displayed in the explorer. I'm leaving this issue open for the time being as we still have some odd behavior in the mobile and web wallet views for the NFTs, the body of this bug is still relevant.

**Comment by ghost** [comment]
I believe this is all very clear now. We've confirmed many times over now the differences between the Counterfactual NFTs and deployed NFTs. Other display issues are mostly sorted out now, so this is no longer muddying the waters.

Closing.
