### ISSUE TITLE
NFT count does not update after transferring an NFT unless the page refreshed

### ISSUE THREAD

**Issue by sk33z3r** [Loopring/loopring-wallet-feedback#189]
The repro assumes you have an NFT in your wallet with at least 2 or more copies.

**Repro**:

1. Connect wallet with the web app
2. Go to **My NFTs**
3. Find your NFT in the list
_OBSERVE_: Take note of the NFT count. In my gif it is 44
4. Click your NFT to see its info
5. Click **Transfer** button
6. Enter information for the transfer, then click **Mint My NFT** button
7. Click **Confirm** button and sign the transaction
8. Click **Close** button when success message appears
_OBSERVE_: You are returned to the **My NFTs** page, take note of the count on your NFT

**Expected**:
My NFT count is less what I sent (if I sent 1, then I would expect the count to be 43 now)

**Actual**:
The NFT count remains what it was at step 3

**Additional Notes**:
* A refresh of the page fixes will show the correct number.
* The quantity in the NFT's info modal is also affected by this bug.
* I can transfer an entire set of 100+ NFTs without refreshing the page, and the count always remains the same

![gif_20220303_180127](https://user-images.githubusercontent.com/20587571/156667942-2759fb49-6e79-43b9-ac7e-985b9d2c7cec.gif)

**Comment by ghost** [comment]
I've noticed that the page partially refreshes now when transferring an NFT multiple times in one session. Typically I see the number update now. However, there are some other issues where the interface breaks down after 4 or 5 transfers in a row.

Closing this issue.
