### ISSUE TITLE
Better material for understanding guardians, locking, etc. 

### ISSUE THREAD

**Issue by mfinestone** [Loopring/loopring-wallet-feedback#19]
This can be in app, or a blog post we link to.

**Comment by mfinestone** [comment]
![image](https://user-images.githubusercontent.com/36642873/100372823-d2709600-2fd7-11eb-8a88-61383d563d97.png)

**Comment by odesium** [comment]
https://desk.zoho.com/portal/loopring/en/kb/loopring/smart-wallet-mobile-app/guardians-security
