### ISSUE TITLE
Using WalletConnect on web wallet UI fails

### ISSUE THREAD

**Issue by sk33z3r** [Loopring/loopring-wallet-feedback#194]
# Issue 1

Several folks have been reporting this issue. It happens more often than not, and it takes several re-tries to get yourself connected and logged in. It's almost impossible for some people to connect and mint or view their wallet if they are on mobile.

**Repro**:

1. Open https://loopring.io/#
2. Launch App
3. Click **Connect Wallet**
4. Check the agreement, choose **WalletConnect**
5. Scan the QR code that appears with the mobile app
_OBSERVE_: You are connected, but need to Unlock
6. Click **Unlock**
_OBSERVE_: Mobile wallet asks you to sign the message
7. Sign the message

**Expected**:
Wallet unlocks and I can click around and view my mobile wallet details

**Actual**:
The window hangs on a loading GIF, and MetaMask opens

**Notes**:
* It's possible that this only affects people that have MetaMask installed in their browser.

![gif_20220316_113934](https://user-images.githubusercontent.com/20587571/158629973-dea586ac-eeab-4bc0-846c-1c6222ab8201.gif)

# Issue 2

If you do not have MetaMask installed, and are able to login with WalletConnect, some actions do not function.

1. Open https://loopring.io/# and connect wallet with WalletConnect
2. Go to My NFTs in the Wallet
3. Choose and NFT and click Transfer
4. Fill the form and click Transfer
_OBSERVE_: User is asked to sign message on the mobile app
5. Sign the message

**Expected**:
The NFT transfer is successful and a message confirms it

**Actual**:
The transfer fails with the message "Submit info has error"

**Notes**:
* Tried several browsers, but the issue was the same each time.
* Connecting with MetaMask does not have this issue
* Transferring within the mobile wallet works without issue

The Error Response:

![image](https://user-images.githubusercontent.com/20587571/158717701-14a65992-8867-445c-9f6b-d98c43aa2a9f.png)

![image](https://user-images.githubusercontent.com/20587571/158717668-71d4e555-bd94-4347-bed6-d6975f43b152.png)

**Comment by sk33z3r** [comment]
It appears that WalletConnect has some general issues across the site as a whole. New issue added to this master list.

**Comment by sk33z3r** [comment]
If you have MetaMask installed and want to use WalletConnect, you can workaround it with this:

1. Launch the app and connect with MetaMask
2. Unlock with MetaMask
3. Disconnect MetaMask
4. Connect with WalletConnect

It seems to work this way. If you close your browser or otherwise clear cookies, it seems to make the issue return.

**Comment by ghost** [comment]
I believe the issues here are sorted and have been for a couple of days now. Closing.
