### ISSUE TITLE
"Your Minted NFT does not contain Metadata or media information" when trying to transfer an NFT

### ISSUE THREAD

**Issue by Nimai85** [Loopring/loopring-wallet-feedback#195]
NFT shows fine on https://explorer.loopring.io/nft/0xfbae21ffe4216f2fb8313ddc1ac7850791d61b85-0-0x28ba1bda05c80302285550cd0173f4647499e0b0-0x255bab561df9d37137e31ee5ff1cb7cc4ca22680d8c01bfaae2a7adc63f93662-0
Logging in L2 wallet on chrome (v99.0.4844.82 on windows 11) or android wallet app (v2.1.5.181) the nft shows no image.
When trying to transfer the NFT i receive the confirmation message: "Your Minted NFT does not contain Metadata or media information"

**Comment by ghost** [comment]
I ran into this same issue a few times as well, but generally if I waited for a few minutes with the NFT onscreen it would eventually load. Some times I needed to refresh the page.

There are some bandaids they put into to place in the NFT View to fix this issue: #185 

As a result of that mixed with using ipfs.io, the interface breaks down a lot: #186 

As far as your images not showing in the mobile app, those issues are recorded here:
#180 
#179 
#198

**Comment by ghost** [comment]
@Nimai85 Could you update your mobile app to v2.2.2.188 and try this again? If it is resolved, please close. Thank you!

**Comment by Nimai85** [comment]
Everything Is fine now with the latest version, thank you!
