### ISSUE TITLE
Wrong NFT delivered during transfer using the Web Wallet UI

### ISSUE THREAD

**Issue by ghost** [Loopring/loopring-wallet-feedback#199]
I don't have a solid reproduction yet. I am still working on nailing it down. I was the intermediary for a Loophead trade which was bad in itself, but there could be other folks where this is happening and it's not very obvious that it is occurring because of how poorly organized the NFT view is in any wallet.

I believe these to be the pre-requisites for the bug to occur:
* WalletConnect w/ iOS or Android. I have not been able to replicate in my dev MetaMask. I will need to spend time replicating in my Android wallet.
* A lot of NFTs, especially larger filesizes. My Android wallet has upwards of 400 NFTs, some are big GIFs or massive images. This results in 29 pages in the NFT view on the Web Wallet. My dev MetaMask also only has 2 pages of NFTs.

**Repro**:
1. Go to loopring.io and Connect/Unlock wallet using WalletConnect
2. Go to L2 Wallet > My NFT
3. Try to find your NFT
_OBSERVE_: Possible to run into several bugs: #186 #167 #174
4. Once you find the NFT, click it to open the modal and see the NFT info
5. Click **Transfer**, fill out the form
6. Click **Transfer**, **Confirm**, then sign the transaction

**Expected**:
Successful transfer modal appears, receiving wallet has the NFT in their wallet

**Actual**:
Successful transfer modal appears, receiving wallet has a different NFT in their wallet

**Notes**:
* I believe the issue has a lot to do with React and issue #186 . The interface loads _excruciatingly_ slow on a good day because of this. When you try to move through the paginated view, sometimes artifacts from previous pages remain on screen for several seconds before actually loading the right data for that page.
* In order to trip up the system, I believe that speed is also involved. Let's say my NFT is on page 20. If I go to the last page first, and then start clicking the prev page button rapidly to get to page 20, then it takes minute but eventually I see the NFTs for that page. This is precisely what I did for a Loophead trade, but the receiving wallet got one of my personal NFTs and the Loophead never left my wallet.

This is what I saw when I was transferring:

![image](https://user-images.githubusercontent.com/20587571/162561195-42f6fc41-5519-4cbf-a9ae-be651301c7fa.png)

This is what the other wallet received (NFT on the left):

![image](https://user-images.githubusercontent.com/20587571/162561265-67341fae-5205-47d2-b27b-742484cdacd0.png)

**Comment by ghost** [comment]
I have had this occur to me twice tonight so far. I am in the middle of trying to send 159 items.

* I have 533 NFTs in my wallet, so the web wallet view gets split into 45 different pages.
* The NFTs I need to transfer end up around pages 20 - 30
* If I click through each page, wait for all the NFTs to load, then move to the next page, I can usually only get to page 10 or so before the whole interface breaks down and I need to refresh and start over.
* If I click very quickly through the pages to the page I know I need to get to (for example 22), then once I get to that page it takes a long while for any of the images to load.
* Pulling up the NFT info shows all the correct data on screen, the name/description/image is all what I expect.
* When the NFT thumbnails list updates, I see it shift, but the NFT I was just viewing doesn't disappear from the list. A different one disappears from the list.

Both times it happened, it occurred after clicking through each page rapidly.

**Comment by ghost** [comment]
This occurred to me just now, and speed of clicking through pages + large amount of NFTs are definitely part of the reproduction. That coupled with ipfs.io I believe is exacerbating the issue.

**What happened:**

1. Connect wallet to web app
2. Go to L2 Wallet > My NFT
3. Click Page 40, then back track until I reached page 33 (the NFT I needed to send is on page 33)
_OBSERVE_: It takes a while for images to populate. On occasion upwards of 60 seconds for everything to load. Some pages I let load entirely, some pages I just clicked through to the next without letting them fully load
4. Find the NFT I needed to send (Sacred Bodies # 41). I found it by looking for its picture and confirming the name
5. Click the NFT to bring up the information with Transfer button
_OBSERVE_: The info is still showing me the correct name (Sacred Bodies # 41), correct image, correct description, and correct token ID
6. Do the transfer process and wait until you receive the TX link

**Expected**:
As the page refreshes, Sacred Bodies # 41 disappears from my NFT list in the wallet

**Actual**:
Sacred Bodies # 41 remains in the wallet, I don't see any others that disappeared

This is the tx: https://explorer.loopring.io/tx/20578-2

This is the NFT I was trying to send: 
https://explorer.loopring.io/nft/0x0f6ef4f04f14af17140d329c769f936776b4c36f-0-0x5c87ec90db117509fd654ed7440524323e647394-0x30e9ef963020268ad03ee6769cdafb2157d4ee69e94db1013425d120ab38916e-10

This is the NFT that actually got send:
https://explorer.loopring.io/nft/0x9da2fad64e6e803e0337582301aeb3995981ea07-0-0x3cbdec201b15bdf4cd65bc1c9a4f93c30a5dce20-0xe5431864bbe70533ea1ee30e003ff0560e37825afcff1d9ebada73f8abda292e-0

Video of the pagination behavior described at step 3:

https://user-images.githubusercontent.com/20587571/167977106-e283aa1e-3d40-4715-9da8-a350fcb4d494.mp4

**Comment by rosareth** [comment]
@adam-bro this bug is imo really important to look at rn. Sending the wrong NFT could be really painful and a show-stopper for the trust to this functionality

**Comment by windatang** [comment]
53856f133a667bc4dd50b4c5ee86268e3efad5ad
