### ISSUE TITLE
User control of setting gas fee

### ISSUE THREAD

**Issue by mfinestone** [Loopring/loopring-wallet-feedback#20]
Some users have expressed they want to be able to pay a lower gas fee to go from L1 - L2, if they are not in a rush, and don't want to pay so much gas. They cannot adjust it currently. 

![image](https://user-images.githubusercontent.com/36642873/100273000-11481280-2f2a-11eb-8e46-cbea07223aa3.png)

or even the ability to have two types, similar to fast withdrawal mechanism. to go immediate, or wait for a batch. (unsure if that is feasible for deposits). 

![image](https://user-images.githubusercontent.com/36642873/100273032-202ec500-2f2a-11eb-991b-3af6234c507f.png)

**Comment by adamchen0510** [comment]
Yes, we are considering to add this feature. But it's more complex than traditional wallet, maybe add this feature after several weeks.

**Comment by marceljay** [comment]
I just created my wallet. Moving LRC would cost me 0.042 at current prices (is that really the answer? ;-)) 
So please add custom gas settings. L2 and smart wallets are currently anyway mainly used by people who know what they're doing.

**Comment by ablankstory** [comment]
Option for Normal vs. Fast has been implemented.
