### ISSUE TITLE
NFT Description Improperly Handling Apostrophes

### ISSUE THREAD

**Issue by chrisdudek** [Loopring/loopring-wallet-feedback#204]
![image](https://user-images.githubusercontent.com/11835064/166447914-1d9c4658-87af-46f1-9c97-2272082589ba.jpeg)

It appears that the NFT Description section within the Wallet is improperly handling an apostrophe.

Thanks.

**Comment by chrisdudek** [comment]
Also appears to be an issue on Web. 

![image](https://user-images.githubusercontent.com/11835064/166448797-7ae9ba9b-cecd-44bc-bb17-e463c2bdd9de.jpeg)

![image](https://user-images.githubusercontent.com/11835064/166448815-2fb58cf8-cc8f-4177-8589-a57ef5f82f93.jpeg)

**Comment by fudgebucket27** [comment]
The apostrophe issue also occurs if it is in the name 
![image](https://user-images.githubusercontent.com/5258063/180929893-3b7d42ae-1d65-4284-ad9c-3a53340461c8.png)

The name of this one I specified as "Fudgey's Weather - Townsville" in the metadata
