### ISSUE TITLE
List of near term questions for Nov 27th

### ISSUE THREAD

**Issue by mfinestone** [Loopring/loopring-wallet-feedback#21]
Does the Loopring guardian count as one of the 3 needed for the mining bonus? (Shadon)

Can you have the same Loopring wallet on 2 phones? By recovering it on the send device, does it lock first? (Matheus)

Should I send all my assets to L2 or will I have to bring them back to L1 for the update on the 27th? i.e. Can I migrate to 3.6 from L2 to L2 within the wallet, or must withdraw first, and spend gas?

**Comment by adamchen0510** [comment]
1 Yes
2 Not support same wallet on different phones. If recover on new phone, the previous phone can not use the wallet.
3 Don't need send L2 to L1, we'll auto do it in new app and pay by Loopring.
Will auto withdraw from v3.1 L2 to L1(Loopring pay), 
and user need manual deposit to 3.6 L2(User pay).
