### ISSUE TITLE
Moving LRC from L1 to L2

### ISSUE THREAD

**Issue by a-triant** [Loopring/loopring-wallet-feedback#217]
Tried to move three times all the amount unsuccessfully, every time it moved only 7 LRC instead of the four digit amount. The transaction fees has been paid with points. 

Was able successfully move only when changed fees to be paid with ETH instead of the points.

![photo_2022-08-17_13-07-06t](https://user-images.githubusercontent.com/22340405/185093250-21cec86d-b143-4484-b176-97a6b5dc17de.jpg)

**Comment by ablankstory** [comment]
Is this still an issue or are we okay to resolve? Thanks!

**Comment by a-triant** [comment]
> Is this still an issue or are we okay to resolve? Thanks!

Don't have idea, since I don't need anything to move from L1 to L2.

Before i had wasted around 3k points, every time it's moved 7LRC instead of XXXX, after three times, i tried to pay the fees with ETH instead of points and it worked. So the issue was moving LRC from L1 to L2 paying by points.
