### ISSUE TITLE
Several errors using European system language

### ISSUE THREAD

**Issue by tiziano-carrer** [Loopring/loopring-wallet-feedback#25]
I solved all the issues changing system language from Italian to English/USA
Also German language is affected

**Comment by mfinestone** [comment]
Thanks for sharing the solution!

**Comment by mfinestone** [comment]
Seems time must also be changed to 12 hour, AM/PM format to solve this issue (if user is on 24 hour time, may not work).

**Comment by tiziano-carrer** [comment]
For me it works also with 24 hours time format.. 🙄

**Comment by adamchen0510** [comment]
The last release 1.0.59 fixed this issue, thanks for your feedback!
