### ISSUE TITLE
Transfers from L2 to external L1 account not allowed.

### ISSUE THREAD

**Issue by tiziano-carrer** [Loopring/loopring-wallet-feedback#28]
Protocol 3.6 should allow those transfers, but now it gives this error:

![IMG_20201128_104545](https://user-images.githubusercontent.com/13995085/100499122-5442f980-3167-11eb-9062-e6bad98a1424.jpg)

**Comment by adamchen0510** [comment]
Yes, 3.6 can do this, will add this feature to app later.

**Comment by odesium** [comment]
Send to any L2 setting added.
