### ISSUE TITLE
Explain why we need email/phone number

### ISSUE THREAD

**Issue by mfinestone** [Loopring/loopring-wallet-feedback#30]
Many people in crypto are averse to disclosing this info. Let's provide a little explanation as to why we need it, so it comforts them, and they see it is mainly for their own benefit. 

I believe the reasons are:

1. Loopring Guardian. So if they lose access to their mobile wallet before setting guardians, we can help them recover it. 

2. Sybil-resistance. So we don't spin up contracts and waste gas for nothing. (although this is obviously not airtight, since people can spin up email addresses trivially).

**Comment by adamchen0510** [comment]
Yes, both your points are correct.
1 By phone or email, we'll auto add Loopring official guardian to the user wallet. So if user delete the app or lost the phone, he can easy to recover the wallet if he didn't added more guardians after create wallet.
2 As we'll pay gas for the wallet creation, we need user provider more info to avoid spin up.

And if user don't believe in Loopring Official Guardian, he can add more guardians to  avoid Official Guardian do some evil things, if he add 2 more guardians, he can totally not use Loopring Official Guardian to recover.
If user believe in official guardian, he can use official guardian service, like big money transfer notification, add guardian notification and recover his wallet.
But we recommend user to add 2 more guardians to make his wallet safer, to avoid his wallet would be recovered if our server attacked.
