### ISSUE TITLE
Out of Gas 

### ISSUE THREAD

**Issue by VVander** [Loopring/loopring-wallet-feedback#40]
I tried to make and fund a new wallet today. Tried twice, out of gas error for both transactions... finally I set the gas limit high enough on the 3rd one for it to go through. I suggest updating the new wallet deposit notification in app to recommend a specific gas limit. I entered 52000 manually for that 3rd transaction to post, even though I see after making the wallet that the limit only needs to be 23,300.

**Comment by adamchen0510** [comment]
You mean sent some token to Loopring Wallet out of gas? Would you please provide the hash?

**Comment by ablankstory** [comment]
Note shown when receiving that gas limit should be set to 30,000.
