### ISSUE TITLE
explain that private key seen in wallet is not L1 private key

### ISSUE THREAD

**Issue by mfinestone** [Loopring/loopring-wallet-feedback#47]
some users copy those keys down thinking their security relies on it. let's make a little label saying this is L2 stuff, not how you recover a wallet... 

![image](https://user-images.githubusercontent.com/36642873/103826492-ed0d4480-5044-11eb-947a-280373cd2ff7.png)

**Comment by adamchen0510** [comment]
Yes, this is L2 info

**Comment by mfinestone** [comment]
To the existing wording, let's please add as a final statement:

"The private key below is not your Ethereum address private key. It is the private key for your Loopring L2 account. If someone has this information, they can make L2 txs, they cannot access or wipe out your L1 assets."

**Comment by dong77** [comment]
This is noted and will be reflected in our new UI
