### ISSUE TITLE
Show suggested gas price

### ISSUE THREAD

**Issue by enuoCM** [Loopring/loopring-wallet-feedback#57]
It's better to just show the suggested gas price and the estimated gas amount when transferring between L2 and L1 , even user cannot set the gas price currently.  Show information like https://etherscan.io/gastracker is much better.

**Comment by adamchen0510** [comment]
we've added the gasPrice when L1->L2 and L1->L1, you can check in the newest version.
And now only has two level to choose, we'll add more levels later
