### ISSUE TITLE
Add additional Withdrawal confirmation screen and warning.

### ISSUE THREAD

**Issue by odesium** [Loopring/loopring-wallet-feedback#71]
A number of users are Withdrawing assets from L2 to L1 and in particular exchanges. However some users are mistakenly sending from L2 to L2 of exchanges and other users.

An additional warning and confirmation screen should be added to highlight the sending:
From Loopring 
To Lx Address
Confirmation of fee

Note: Please ensure for withdrawals to exchanges that the exchange accepts deposits from Smart Contract Wallets and you have checked you are sending to the correct L1 or L2 address of the recipient.

After this screen. The below should be Next and then the above Confirm.

![loop](https://user-images.githubusercontent.com/56487762/111369269-c6940700-868e-11eb-848c-9b60b539aecc.PNG)

**Comment by Now-GIT** [comment]
Over the past few months, I recall seeing three complaints regarding funds not being accessible when sending out from L2:

1. Sending L2 -> L2 to CEX Coinbase
2. Sending L2 -> L2 to Celsius wallet
3. Sending L2 -> L1 to an address that was said to not be able to receive from a smart contract.

For the note, wouldn't put "smart contract wallet" in capital letters and would remove word "wallet" for any note made for web exchange users.

I wrote out the following suggestion for consideration, which still might not be perfect:

Some addresses are not yet set up to properly receive the selected transaction type (such as addresses from several centralized centralized exchanges, e.g., Coinbase): L2 -> L2. If you are uncertain, please inquire with the address provider or you can choose the following option instead." Would then need L2 -> L1 option.

I'm not sure whether an additional note would be required about sending from a smart contract for an L2 -> L1 transaction.
