### ISSUE TITLE
Wallet balances in $ frequently showing wrong value

### ISSUE THREAD

**Issue by brentmw1** [Loopring/loopring-wallet-feedback#80]
A couple users have said that their balances in the app show with incorrect values, which change when refreshing the balances page. It seems to snap to some constant values. Are values still hard coded somewhere that makes it maybe show those values if it's not able to grab the dynamic values?

**Comment by adamchen0510** [comment]
fixed. As one of our server did't update the price and keep an old price, other servers use the latest price, so had this issue.
