### ISSUE TITLE
Its not possible to enter ENS at wallet creation

### ISSUE THREAD

**Issue by psclahr** [Loopring/loopring-wallet-feedback#94]
According to this guide: https://blogs.loopring.org/install-loopring-wallet-en/ it should be possible to enter the wallet name, but the step is skipped and the order details are shown. At the end you need to pay the creation fees, but what if you want to choose a ENS longer than seven characters to avoid fees?

**Comment by odesium** [comment]
ENS is now moved to after wallet creation.
