### ISSUE TITLE
iOS App 1.0.26 - No Indication of Fee Amount

### ISSUE THREAD

**Issue by chrisdudek** [Loopring/loopring-wallet-feedback#96]
It appears the iOS app was recently updated. When going to create a Smart Wallet, it no longer shows how much it will actually cost. As we all know, gas fees change substantially throughout the day and weekends. I think it is a step backwards to not indicate to the end user how much it will charge them in the given token to create the Wallet.

![551764DF-63C9-46EB-9AD5-A52049F8857A](https://user-images.githubusercontent.com/11835064/141643758-6ad6470b-d9d7-4755-ae3d-695926507161.png)
![8221773C-3F76-42B9-922C-F97F77FED7FB](https://user-images.githubusercontent.com/11835064/141643759-a966b794-8c3b-49db-8a29-1630f67abe65.png)

**Comment by odesium** [comment]
App updated
