### ISSUE TITLE
Spelling error typo on wallet app

### ISSUE THREAD

**Issue by mattyblrc** [Loopring/loopring-wallet-feedback#97]
There appears to be a typo spelling error in the wallet app in the Expired notice popup. "Contanct us" should be changed to "Contact us". "please..." should be changed to "Please..."

[A screenshot of the typos](https://i.imgur.com/wMYVT2g.png)

**Comment by mattb150** [comment]
A second type exists on the Migrate Wallet page: "Loppring" should be changed to "Loopring"

[A screenshot of the typo](https://i.imgur.com/DYfRs3V.jpeg)

**Comment by a-triant** [comment]
> "Contanct us" should be changed to "Contact us"

"Contact Us"  maybe would be better.
