### ISSUE TITLE
Red Packet unsupported token.

### ISSUE THREAD

**Issue by a-triant** [Loopring/loopring-wallet-feedback#99]
I have received some DPR token from red packet, as soon as I click on Withdraw button it quickly opens and close and a message comes out "This token is not supported withdrawal" So I cannot withdraw it or send it, looks strange, if it's not supported then how the other guy send it? how to get rid of it?

![IMG_3560](https://user-images.githubusercontent.com/22340405/142753212-932969d8-6098-4569-96e8-cd209d56f303.PNG)

**Comment by TaoGe96** [comment]
duplicated issue

**Comment by a-triant** [comment]
Where is the duplicate issue?

**Comment by a-triant** [comment]
> duplicated issue

Where is the duplicate issue?

**Comment by incognitols** [comment]
Duplicated issue
